image: busybox

pages:
  stage: deploy
  script:
    - echo "see https://gitlab.com/pages/plain-html"
  artifacts:
    paths:
    - public
    expire_in: 1 day
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

